version: '3.8'

services:
  # Banco de dados PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: kanban_postgres
    environment:
      POSTGRES_DB: kanban_db
      POSTGRES_USER: kanban_user
      POSTGRES_PASSWORD: kanban_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - kanban_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kanban_user -d kanban_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Aplicação Node.js
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kanban_app
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://kanban_user:kanban_password@postgres:5432/kanban_db
      - PORT=5000
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
      - ./public/uploads:/app/public/uploads
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - kanban_network
    command: npm run dev
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  kanban_network:
    driver: bridge